### ISSUE TITLE
imagine.sdprem not working

### ISSUE THREAD

**Issue by pjrenzov** [ItsCEED/Imaginepy#14]
An error occurred while making the request: 400 Client Error: Bad Request for url: https://inferenceengine.vyro.ai/sdprem

**Comment by raymerjacque** [comment]
this happens when you send a request twice. 

meaning you generate an image, and then try to generate a second image... 

if you generate an image, close the app and open the app again and then generate another image it works fine...

hopefully someone can take a look at why this is happening. seems the inputs are not being reset or something after generating the first time...

**Comment by pjrenzov** [comment]
Traceback (most recent call last):
  File "/home/aviral/.local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aviral/.local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aviral/.local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aviral/.local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/aviral/final-wa-bot/main.py", line 173, in test
    tshirts = getTshirt(request.args.get("prompt"), request.args.get("number"))
  File "/home/aviral/final-wa-bot/tnl/imagine.py", line 82, in getTshirt
    result = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/aviral/final-wa-bot/tnl/imagine.py", line 13, in create
    img_data = imagine.sdprem(
  File "/home/aviral/final-wa-bot/tnl/im/Imagine.py", line 102, in sdprem
    raise ConnectionError(f"An error occurred while making the request: {e}")
ConnectionError: An error occurred while making the request: 400 Client Error: Bad Request for url: https://inferenceengine.vyro.ai/sdprem



This was the error. No idea what should I close here. It's a local server I am using for my siblings to create images.

**Comment by ItsCEED** [comment]
All should be good now.
